<?php
class modelacuerdonomisional_model extends CI_Model {

    function __construct() {
        parent::__construct();
    }

    function consultadatosnomisional($liquidacion){
        
        $this->db->join('EMPRESA','EMPRESA.CODEMPRESA = LIQUIDACION.NITEMPRESA');
        $this->db->where('LIQUIDACION.NUM_LIQUIDACION',$liquidacion);
        $datos = $this->db->get('LIQUIDACION');
        
//        echo $this->db->last_query();die;
        
        return $datos->result_array();
    }
        function acuerdosjuridicos(){
//        echo "sdfsdfsdfffffff";
//        die;
        $this->db->select('INGRESOACUERDOJURIDICO.NUMERO_PROCESO,EMPRESA.CODEMPRESA,EMPRESA.RAZON_SOCIAL,INGRESOACUERDOJURIDICO.EXCEPCION,INGRESOACUERDOJURIDICO.NUM_LIQUIDACION,'
                . 'INGRESOACUERDOJURIDICO.COD_ACUERDOJURIDICO,GARANTIA_ACUERDO.NUM_LIQUIDACION AS CODIGO,'
                . 'EXCEPCIONESACUERDOJURIDICO.EXCEPCION EXC,INGRESOACUERDOJURIDICO.NUMERO_RESOLUCION,INGRESOACUERDOJURIDICO.VALOR_A_CALCULAR,'
                . 'INGRESOACUERDOJURIDICO.CUOTAS,AUTORIZACION_CUOTAS.COD_ACUERDOJURIDICO AS ESPERA,'
                . 'INGRESOACUERDOJURIDICO.ABONO_INICIAL,INGRESOACUERDOJURIDICO.VALOR_INTERESES');
        $this->db->distinct('EMPRESA.CODEMPRESA,EMPRESA.RAZON_SOCIAL,INGRESOACUERDOJURIDICO.EXCEPCION,INGRESOACUERDOJURIDICO.NUM_LIQUIDACION,'
                . 'INGRESOACUERDOJURIDICO.COD_ACUERDOJURIDICO,GARANTIA_ACUERDO.NUM_LIQUIDACION AS CODIGO,'
                . 'EXCEPCIONESACUERDOJURIDICO.EXCEPCION EXC,INGRESOACUERDOJURIDICO.NUMERO_RESOLUCION,INGRESOACUERDOJURIDICO.VALOR_A_CALCULAR');
        $this->db->join('EMPRESA','EMPRESA.CODEMPRESA = INGRESOACUERDOJURIDICO.CODEMPRESA');
        $this->db->join('GARANTIA_ACUERDO','GARANTIA_ACUERDO.NUM_LIQUIDACION = INGRESOACUERDOJURIDICO.NUM_LIQUIDACION','LEFT');
        $this->db->join('EXCEPCIONESACUERDOJURIDICO','EXCEPCIONESACUERDOJURIDICO.COD_ACUERDOJURIDICO = INGRESOACUERDOJURIDICO.COD_ACUERDOJURIDICO','LEFT');
        $this->db->join('AUTORIZACION_CUOTAS','AUTORIZACION_CUOTAS.COD_ACUERDOJURIDICO = INGRESOACUERDOJURIDICO.COD_ACUERDOJURIDICO','left');
//        $this->db->where("INGRESOACUERDOJURIDICO.CODEMPRESA NOT IN (SELECT NITEMPRESA FROM ACUERDOPAGO WHERE JURIDICO = 2)");
        
        $acuerdo = $this->db->get('INGRESOACUERDOJURIDICO');
        
        $datos = $acuerdo->result_array();
        
//        echo $this->db->last_query();
        
        return $datos;
        
    }
}